# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       'DORY'
email:       'emjeon93@gmail.com'
description: '도리개발자블로그'
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://xx4159.github.io/' # The base hostname & protocol for your site
twitter:     'https://twitter.com/xx4159'
github:      'https://github.com/xx4159'
instagram:   'https://www.instagram.com/x.x4159/'
facebook:    'https://www.facebook.com/x.x4159'

markdown:  kramdown
permalink: pretty
paginate:  10

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

remote_theme: aspirethemes/type
